#! /bin/bash
gsed -i -E 's/Théorème(.*)\n/\\begin{thm}\1\\end{thm}/g' *.tex
gsed -i -E 's/⇒/\\rigtharrow\~/g' *.tex
gsed -i -E 's/≠/\\neq\~/g' *.tex
gsed -i -E 's/∅/\\varnothing\~/g' *.tex
gsed -i -E 's/π/\\pi\~/g' *.tex
gsed -i -E 's/→/\\rightarrow\~/g' *.tex
gsed -i -E 's/ℕ/\\mathbb{N}\~/g' *.tex
gsed -i -E 's/∃/\\exists/g' *.tex
gsed -i -E 's/ℛ/\\mathcal\{R\}/g' *.tex
gsed -i -E 's/∈/\\in/g' *.tex
gsed -i -E 's/≼/\\leqslant/g' *.tex
gsed -i -E 's/⇔/\\Leftrightarrow/g' *.tex
gsed -i -E 's/\\textbackslash\{\}/\\/g' *.tex
gsed -i -E 's/\\mathop\\\{(.*)\\\}/\1\~/g' *.tex
gsed -i -E 's/∀/\\forall\~/g' *.tex
gsed -i -E 's/↦/\\mapsto\~/g' *.tex
gsed -i -E 's/≺/\\prec\~/g' *.tex
gsed -i -E 's/ℝ/\\mathbb{R}\~/g' *.tex
gsed -i -E 's/⊂/\\subset\~/g' *.tex
gsed -i -E 's/λ/\\lambda\~/g' *.tex
gsed -i -E 's/∂/\\partial~/g' *.tex
gsed -i -E 's/\\mathrel\\\{(.*)\\\}/\1/g' *.tex
gsed -i -E 's/ℰ/\\mathcal\{E\}/g' *.tex
gsed -i -E 's/φ/\\phi/g' *.tex
gsed -i -E 's/\\\{C\\\}\\\^\{\}\\\{1\\\}/\\mathcal\{C\}\^1/g' *.tex
gsed -i -E 's/∘/\\cdot/g' *.tex
gsed -i -E 's/∑/\\sum/g' *.tex
gsed -i -E 's/mathop//g' *.tex
gsed -i -E 's/\\\{//g' *.tex
gsed -i -E 's/\\\}//g' *.tex
gsed -i -E 's/β/\\beta~/g' *.tex
gsed -i -E 's/α/\\alpha~/g' *.tex
gsed -i -E 's/\\ldots\{\}/\\ldots/g' *.tex
gsed -i -E 's/([!/]*)\~\_/g' *.tex
gsed -i -E 's/\~\_/\_/g' *.tex
gsed -i -E 's/([!/]*)\~\^/g' *.tex
gsed -i -E 's/−/-/g' *.tex
gsed -i -E 's/ξ/\\xi/g' *.tex
gsed -i -E 's/\\&/\&/g' *.tex
gsed -i -E 's/\\begineqnarray\*/\\begin\{align\*\}/g' *.tex
gsed -i -E 's/\\endeqnarray\*/\\end\{align\*\}/g' *.tex
gsed -i -E 's/⊕/\\oplus~/g' *.tex
gsed -i -E 's/∞/\\infty~/g' *.tex
gsed -i -E 's/ℂ/\\mathbb{C}/g' *.tex
gsed -i -E 's/χ/\\chi/g' *.tex
gsed -i -E 's/\\\^\{\}/\^/g' *.tex
gsed -i -E 's/\\mathrmtr/\\mathrm\{tr\}/g' *.tex
gsed -i -E 's/\\mathrmdet/\\mathrm\{det\}/g' *.tex
gsed -i -E 's/\\mathrmSp/\\mathrm\{Sp\}/g' *.tex
gsed -i -E 's/ε/\\epsilon/g' *.tex
gsed -i -E 's/μ/\\mu/g' *.tex
gsed -i -E 's/∪/\\cup/g' *.tex
gsed -i -E 's/≤/\\leq/g' *.tex
gsed -i -E 's/\\upsilon/\\cup/g' *.tex
gsed -i -E 's/\\geq/\\leq/g' *.tex
gsed -i -E 's/↗/\\nearrow/g' *.tex
gsed -i -E 's/↘/\\searrow/g' *.tex
gsed -i -E 's/∫/\\int/g' *.tex
gsed -i -E 's/η/\\eta/g' *.tex
gsed -i -E 's/×/\\times/g' *.tex
gsed -i -E 's/∩/\\bigcap/g' *.tex
gsed -i -E 's/θ/\\theta/g' *.tex
gsed -i -E 's/ψ/\\psi/g' *.tex
gsed -i -E 's/α/\\alpha/g' *.tex
gsed -i -E 's/β/\\beta/g' *.tex
gsed -i -E 's/γ/\\gamma/g' *.tex
gsed -i -E 's/aϜ/\\digamm/g' *.tex
gsed -i -E 's/δ/\\delta/g' *.tex
gsed -i -E 's/ε/\\epsilon/g' *.tex
gsed -i -E 's/ϵ/\\varepsilon/g' *.tex
gsed -i -E 's/ζ/\\zeta/g' *.tex
gsed -i -E 's/η/\\eta/g' *.tex
gsed -i -E 's/θ/\\theta/g' *.tex
gsed -i -E 's/ϑ/\\vartheta/g' *.tex
gsed -i -E 's/ι/\\iota/g' *.tex
gsed -i -E 's/κ/\\kappa/g' *.tex
gsed -i -E 's/κ/\\varkappa/g' *.tex
gsed -i -E 's/λ/\\lambda/g' *.tex
gsed -i -E 's/μ/\\mu/g' *.tex
gsed -i -E 's/ν/\\nu/g' *.tex
gsed -i -E 's/ξ/\\xi/g' *.tex
gsed -i -E 's/π/\\pi/g' *.tex
gsed -i -E 's/ϖ/\\varpi/g' *.tex
gsed -i -E 's/ρ/\\rho/g' *.tex
gsed -i -E 's/ϱ/\\varrho/g' *.tex
gsed -i -E 's/σ/\\sigma/g' *.tex
gsed -i -E 's/ς/\\varsigma/g' *.tex
gsed -i -E 's/τ/\\tau/g' *.tex
gsed -i -E 's/υ/\\upsilon/g' *.tex
gsed -i -E 's/φ/\\phi/g' *.tex
gsed -i -E 's/ϕ/\\varphi/g' *.tex
gsed -i -E 's/χ/\\chi/g' *.tex
gsed -i -E 's/ψ/\\psi/g' *.tex
gsed -i -E 's/ω/\\omega/g' *.tex
gsed -i -E 's/Γ/\\Gamma/g' *.tex
gsed -i -E 's/Γ/\\varGamma/g' *.tex
gsed -i -E 's/Δ/\\Delta/g' *.tex
gsed -i -E 's/Δ/\\varDelta/g' *.tex
gsed -i -E 's/Θ/\\Theta/g' *.tex
gsed -i -E 's/Θ/\\varTheta/g' *.tex
gsed -i -E 's/Λ/\\Lambda/g' *.tex
gsed -i -E 's/Λ/\\varLambda/g' *.tex
gsed -i -E 's/Ξ/\\Xi/g' *.tex
gsed -i -E 's/Ξ/\\varXi/g' *.tex
gsed -i -E 's/Π/\\Pi/g' *.tex
gsed -i -E 's/Σ/\\Sigma/g' *.tex
gsed -i -E 's/Σ/\\varSigma/g' *.tex
gsed -i -E 's/Υ/\\Upsilon/g' *.tex
gsed -i -E 's/Υ/\\varUpsilon/g' *.tex
gsed -i -E 's/Φ/\\Phi/g' *.tex
gsed -i -E 's/Φ/\\varPhi/g' *.tex
gsed -i -E 's/Ψ/\\Psi/g' *.tex
gsed -i -E 's/Ψ/\\varPsi/g' *.tex
gsed -i -E 's/Ω/\\Omega/g' *.tex
gsed -i -E 's/Ω/\\varOmega/g' *.tex
gsed -i -E 's/ℏ/\\hbar/g' *.tex
gsed -i -E 's/ℓ/\\ell/g' *.tex
gsed -i -E 's/ı/\\imath/g' *.tex
gsed -i -E 's/j/\\jmath/g' *.tex
gsed -i -E 's/℘/\\wp/g' *.tex
gsed -i -E 's/ℜ/\\Re/g' *.tex
gsed -i -E 's/ℑ/\\Im/g' *.tex
gsed -i -E 's/∂/\\partial/g' *.tex
gsed -i -E 's/∞/\\infty/g' *.tex
gsed -i -E 's/′/\\prime/g' *.tex
gsed -i -E 's/∅/\\emptyset/g' *.tex
gsed -i -E 's/∀/\\forall/g' *.tex
gsed -i -E 's/∃/\\exists/g' *.tex
gsed -i -E 's/∫/\\smallint/g' *.tex
gsed -i -E 's/△/\\triangle/g' *.tex
gsed -i -E 's/√/\\surd/g' *.tex
gsed -i -E 's/|/\\Vert/g' *.tex
gsed -i -E 's/∥/\\parallel/g' *.tex
gsed -i -E 's/⊤/\\top/g' *.tex
gsed -i -E 's/⊥/\\bot/g' *.tex
gsed -i -E 's/†/\\dag/g' *.tex
gsed -i -E 's/‡/\\ddag/g' *.tex
gsed -i -E 's/♭/\\flat/g' *.tex
gsed -i -E 's/♮/\\natural/g' *.tex
gsed -i -E 's/♯/\\sharp/g' *.tex
gsed -i -E 's/∠/\\angle/g' *.tex
gsed -i -E 's/♣/\\clubsuit/g' *.tex
gsed -i -E 's/♦/\\diamondsuit/g' *.tex
gsed -i -E 's/♥/\\heartsuit/g' *.tex
gsed -i -E 's/♠/\\spadesuit/g' *.tex
gsed -i -E 's/¬/\\neg/g' *.tex
gsed -i -E 's/⋄/\\Diamond/g' *.tex
gsed -i -E 's/℧/\\mho/g' *.tex
gsed -i -E 's/ℏ/\\hslash/g' *.tex
gsed -i -E 's/∁/\\complement/g' *.tex
gsed -i -E 's/‵/\\backprime/g' *.tex
gsed -i -E 's/△/\\vartriangle/g' *.tex
gsed -i -E 's/∅/\\varnothing/g' *.tex
gsed -i -E 's/∕/\\diagup/g' *.tex
gsed -i -E 's/∖/\\diagdown/g' *.tex
gsed -i -E 's/▴/\\blacktriangle/g' *.tex
gsed -i -E 's/▾/\\blacktriangledown/g' *.tex
gsed -i -E 's/▽/\\triangledown/g' *.tex
gsed -i -E 's/⅁/\\Game/g' *.tex
gsed -i -E 's/□/\\square/g' *.tex
gsed -i -E 's/■/\\blacksquare/g' *.tex
gsed -i -E 's/◊/\\lozenge/g' *.tex
gsed -i -E 's/⧫/\\blacklozenge/g' *.tex
gsed -i -E 's/∡/\\measuredangle/g' *.tex
gsed -i -E 's/∢/\\sphericalangle/g' *.tex
gsed -i -E 's/Ⓢ/\\circledS/g' *.tex
gsed -i -E 's/★/\\bigstar/g' *.tex
gsed -i -E 's/Ⅎ/\\Finv/g' *.tex
gsed -i -E 's/ð/\\eth/g' *.tex
gsed -i -E 's/∄/\\nexists/g' *.tex
gsed -i -E 's/ℵ/\\aleph/g' *.tex
gsed -i -E 's/ℶ/\\beth/g' *.tex
gsed -i -E 's/ℸ/\\daleth/g' *.tex
gsed -i -E 's/ג/\\gimel/g' *.tex
